### PR TITLE
remove: `assertIsEntry()`

### PR DESCRIPTION
**Pull request by gaurab-khanal**

### CODE REVIEW

**Comment by iuioiua** [comment]
Please run `deno fmt` to format then `Deno task ok` to check everything else is fine?

**Comment by iuioiua** [comment]
Closes #465

**Comment by gaurab-khanal** [comment]
> Please run `deno fmt` to format then `Deno task ok` to check everything else is fine?
When I ran the above command I got these errors: 
```
(no-unused-vars) `assertNotEquals` is never used
import { assertNotEquals } from "std/testing/asserts.ts";
```

Should I remove that import line and make PR again?

**Comment by iuioiua** [comment]
Yes, please remove that line. No need to create another PR. Please just update this one.

**Comment by gaurab-khanal** [comment]
> Yes, please remove that line. No need to create another PR. Please just update this one.

Just made the changes you mentioned.

**Review by iuioiua — APPROVED** [review]
LTGM! Thank you for your contribution. Much appreciated!

**Pull request merged**
