### PR TITLE
refactor: cleanup `twind`-related functionality

### PR DESCRIPTION
**Pull request by iuioiua**
Everything appears fine after the changes.

### CODE REVIEW

**Comment by iuioiua** [comment]
@lino-levan, looks like `presetAutoprefix()` may not be needed (ref: https://fresh.deno.dev/docs/examples/using-twind-v1).

**Comment by lino-levan** [comment]
`presetAutoprefix()` as its name implies is useful for targeting features that still have prefixes. Definitely a few sharp corners if you choose not to use it (especially around webkit) that I've personally encountered. It isn't strictly necessary but I'd still support having it on by default for beginners.

**Comment by lino-levan** [comment]
To follow up on the comment, I wanted to check that I wasn't going insane, but no there are definitely some tailwind features that need auto-prefixing.

This is one of the sites I helped build (with fresh) in Safari
image

This is how it renders in chrome without the autoprefix
image

This is how it renders in chrome with autoprefix
image

**Comment by iuioiua** [comment]
Oh, interesting... I should add a note where `presetAutoprefix()` was that states this fact. Thanks!

**Comment by lino-levan** [comment]
Definitely one of those bugs that are hard to locate. A note for future maintainers would be really nice!

**Pull request merged**
