### PR TITLE
feature: add Google Analytics plugin

### PR DESCRIPTION
**Pull request by revgum**
Before writing the README updates, I wanted to get this PR out for 👁️ and 🧠 @iuioiua .. I lifted this from the Fresh site and translated it into a plugin here. I've tested it locally, and it's working great with `localhost`. 

This might serve as a good starting point for #72 

Screenshot 2023-09-12 at 5 46 56 AM
Screenshot 2023-09-12 at 5 47 05 AM

### CODE REVIEW

**Comment by iuioiua** [comment]
This looks cool! Let's look at merging this after v1. In the meantime, we can improve on test coverage and whatever else 👍🏾

**Comment by iuioiua** [comment]
Hi @revgum, we're pushing the launch of v1 out till early next year now. And we'd be happy to accept more features before then. Is this PR something you still like to pursue for before v1 is launched?

**Comment by deer** [comment]
@iuioiua, as an alternative, there's something I created: https://deno.land/x/fresh_ga4@0.0.3
Although you probably want me to add some test coverage to my repo as well!

If you want I could create a PR that integrates the existing plugin into saaskit.

**Comment by iuioiua** [comment]
Hi @deer, that looks great! I'd gladly look at a PR that makes use of that plugin. I think this PR has gone stale. And yes, it would be great if there were some tests added, but it might do for now 🙂

**Comment by ooker777** [comment]
UA has officially stopped working. It's time to take this article down or at least have an update to point to working plugins
https://deno.com/blog/ga-with-deno-deploy

**Comment by iuioiua** [comment]
> UA has officially stopped working. It's time to take this article down or at least have an update to point to working plugins https://deno.com/blog/ga-with-deno-deploy

That article is unrelated to this PR (which uses GA4) and this repo.

**Comment by iuioiua** [comment]
Closing in favour of #654. Either way, thank you, @revgum.

**Comment by ooker777** [comment]
oh I didn't know that Deno Saaskit, Deno Blog and Deno Deploy are separate projects. By saying "point to working plugins" I was thinking about the 2 plugins in here

**Comment by iuioiua** [comment]
Ah, I see you created https://github.com/denoland/website_feedback/issues/60. Yep, that's the right way to fix it. Thanks!

**Pull request closed without merging**
