### PR TITLE
Improve user page header

### LINKED ISSUE #468: todo: improve user page header
The current user page header looks like this:
Screenshot 2023-09-01 at 12 05 56 pm

I think it'd look nice if:
- Everything was horizontally aligned to the centre - avatar image on the top, username and badge in the middle and GitHub link on the bottom
- Avatar image was bigger

WDYT, @hashrock?

### PR DESCRIPTION
**Pull request by roberto-morado**
fixes #468 

CC @iuioiua

### CODE REVIEW

**Review by iuioiua — CHANGES_REQUESTED** [review]
I think this whole component could be greatly simplified using `w-full`, `text-center` and `space-y-2` classes and a couple of `<p>` elements. Flex is likely not needed. WDYT?

**Comment by roberto-morado** [comment]
What do you think?

**Review by iuioiua — CHANGES_REQUESTED** [review]
Suggestions:
1. Make username text larger, maybe `text-xl` and remove `<strong />`
2. Maybe put username and GitHub logo on the same line

I'm not certain about these. WDYT?

**Comment by roberto-morado** [comment]
Let me create a few alternatives from which you can choose and we work from there 👍

**Pull request closed without merging**
