### PR TITLE
fix: incorrect month of visits

### PR DESCRIPTION
**Pull request by huai-jie**
close https://github.com/denoland/saaskit/issues/240

### CODE REVIEW

**Review by iuioiua — CHANGES_REQUESTED** [review]
Hey @huai-jie, the issue is that it needs to be presented in a way that makes sense to humans. What if we format the display date using `Date.toLocaleDateString()` instead? Like "Dec 12, 2023" and "Jul 20, 2022". WDYT?

**Comment by huai-jie** [comment]
I like this idea!

But I would still change the way to save the visit `date`.

Because `getUTCmonth()` utilize zero-based indexing, it would consistently cause a discrepancy with the actual month value.

**Comment by iuioiua** [comment]
It looks like we'll need to clear the previous stats data. Is that correct?

**Comment by huai-jie** [comment]
> It looks like we'll need to clear the previous stats data. Is that correct?

Ya ...

**Comment by iuioiua** [comment]
I'll merge once `incrementVisitsPerDay()` is re-enabled.

**Review by iuioiua — APPROVED** [review]
LGTM! Thanks, @huai-jie.

**Pull request merged**
