### PR TITLE
feat: oauth integration

### PR DESCRIPTION
**Pull request by iuioiua**
Implements #13.

Todo:
- [ ] Add a sexy sign-up/sign-in button
- [x] Change to GitHub provider
- [ ] Figure out how things interplay with Stripe
- [ ] Add integration instructions

### CODE REVIEW

**Comment by iuioiua** [comment]
Preview deployment is still not working even though it's a non-forked branch, @kt3k. My understanding is that this should work.

**Comment by kt3k** [comment]
@iuioiua This still looks from your fork (prefixed with your fork name)

Screen Shot 2023-03-24 at 11 54 33

BTW currently `saaskit` project in Deploy doesn't seem setting any env vars. Do you know who manages those?

**Comment by iuioiua** [comment]
Doh! I thought it wasn't a fork 😓

> BTW currently `saaskit` project in Deploy doesn't seem setting any env vars. Do you know who manages those?

It might be Andy. But he hasn't told me of doing so. I'll ask him once he's back.

**Comment by iuioiua** [comment]
#16 is a prerequisite for this PR.

**Comment by iuioiua** [comment]
Closing in favour of #35.

**Pull request closed without merging**
