### PR TITLE
test(utils): increase test coverage

### LINKED ISSUE #267: todo: improve test coverage
The aim is to have [code coverage](https://app.codecov.io/gh/denoland/saaskit) at 100%.

### PR DESCRIPTION
**Pull request by mbhrznr**
Towards #267 

improves overall coverage for `utils` by tackling the uncovered snippets as reported [here](https://app.codecov.io/gh/denoland/saaskit/tree/main/utils). 
as requested by @iuioiua this pr explicitly excludes `utils/db.ts` until the refactoring has been resolved.  
as a drive-by `timeAgo` has been refactored to make use of `std/datetime/difference.ts`.

### CODE REVIEW

**Comment by iuioiua** [comment]
Hey @mbhrznr, do you mind pausing work on this one? I realise that quite a few functions in db do too much. I want to refactor/simplify.

**Comment by mbhrznr** [comment]
> Hey @mbhrznr, do you mind pausing work on this one? I realise that quite a few functions in db do too much. I want to refactor/simplify.

sure thing, just give me a ping whenever you're ready!
also feel free to reach out whenever there's anything else i can support you with.

**Comment by iuioiua** [comment]
If you'd like to do everything else within utils, except for `db.ts`, it should be fine!

**Review by iuioiua — APPROVED** [review]
LGTM! Thank you for this.

**Pull request merged**
