### PR TITLE
refactor: simplify and move `<PostCard />`

### PR DESCRIPTION
**Pull request by iuioiua**
This change:
1. Moves `<PostCard />` into `@/routes/blog/[slug].tsx` as it's the only place that `<PostCard />` is used.
2. Simplifies the signature of `<PostCard />`
3. Removes the US date format setting.

### CODE REVIEW

**Comment by iuioiua** [comment]
PTAL, @kt3k.

**Comment by kt3k** [comment]
> Removes the US date format setting.

I'd prefer to keep `en-US` (or any `en`) locale because most contents and UIs of the site is in English. Showing only date in different locale style can be strange.

**Comment by iuioiua** [comment]
> I'd prefer to keep `en-US` (or any `en`) locale because most contents and UIs of the site is in English. Showing only date in different locale style can be strange.

Fair point. Fixed now.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
