### PR TITLE
refactor: use ULIDs for items

### LINKED ISSUE #475: todo: use ULIDs for item functionality
See #476

### LINKED ISSUE #476: tracking: use ULIDs for KV-related logic
With [ULIDs](https://github.com/kt3k/ulid), we could do the following:
* Remove the need for `*_by_time` KV indexes
* Remove the need for `createdAt` properties
* Maintain chronological order of entries in lists

Todo:
- [x] #473
- [x] #474
- [x] #475

### PR DESCRIPTION
**Pull request by iuioiua**
Please pay attention to the migration script, as it's responsible for migrating all items and votes. I've also changed all instances of `monotonicUlid()` to `ulid()` at there appears to be a bug that prevents `monotonicUlid()` from respecting the `seedTime` parameter.

The migration can be simulated as follows:
1. Switch to **main** branch.
2. Run `deno run db:reset`.
3. Run `deno run db:seed`.
4. Run `deno task start` and navigate to `http://localhost:8000`.
6. Vote some items.
7. Note the voted items and the order of the items feed.
8. Switch to **ulid-items** branch.
9. Run `deno run db:migrate`.
10. Run `deno task start` and navigate to `http://localhost:8000`.
11. Check that the voted items and the order of the items feed are identical to those previously noted.

Closes #475
Closes #476

### CODE REVIEW

**Comment by iuioiua** [comment]
@kt3k, I've made some tweaks. Try now.

**Comment by kt3k** [comment]
Confirmed it's fixed now 👍

**Review by kt3k — APPROVED** [review]
LGTM

**Review by mbhrznr — APPROVED** [review]
just gave the migration a spin.
works like a charm!
well done! 👏 👏

**Pull request merged**
