### PR TITLE
feat: adding item numbering on the homepage

### LINKED ISSUE #211: proposal: complete homepage functionality
This includes:
- [x] Pagination using a `?page=` URL query with items per page length of 10.

### PR DESCRIPTION
**Pull request by brunocorrea23**
Should close #211

### CODE REVIEW

**Comment by iuioiua** [comment]
Hm... Looking at it now, I wonder whether we should have this. Rank being so close to voting score clashes visually. What do you guys think, @brunocorrea23 and @kit?
image

**Comment by huai-jie** [comment]
> and @kit?


Hmm... Looking at it, I wonder is asking me or not ? 🤔

JK

Yup I don't think item numbering is necessary for this case

**Comment by brunocorrea23** [comment]
I think it's nice to have the rank of items. Reaching a higher rank gives an idea of an achievement. I think it's specially useful  when you are not in page number 1. 

I was inspired by Hacker News.
Their solution is visually better probably probably because vote count (or points) is smaller than the item rank.
Screenshot 2023-05-31 at 08 04 30

That being said, no strong conviction here. Either way looks good to me.

**Comment by iuioiua** [comment]
Ok. I'll close this for now. This feature would be nice-to-have but not critical. Either way, much appreciated, @brunocorrea23!

**Pull request closed without merging**
