### PR TITLE
feat: users table

### LINKED ISSUE #370: proposal: add simple users table under charts in admin dashboard
- can we add a users table beneath the charts with some fake users? use case would be the Owner can see/edit/whatever on the SaaS users (see the gif too)

(as example)

image

### PR DESCRIPTION
**Pull request by iuioiua**
This change also:
* Makes the site text size slightly smaller. Previously, it seemed too big.
* Adds a `<TabsBar />` component.

Closes #370

localhost_8000_dashboard_users (2)

### CODE REVIEW

**Review by hashrock — APPROVED** [review]
LGTM!

**Comment by iuioiua** [comment]
@hashrock, would you happen to have any suggestions regarding my previous comment?

**Comment by hashrock** [comment]
@iuioiua hmm I'm not familiar with table styling, so I'm not sure how to solve it.

just a workaround, but how about combine these columns?

image

**Comment by iuioiua** [comment]
> @iuioiua hmm I'm not familiar with table styling, so I'm not sure how to solve it.
> 
> just a workaround, but how about combine these columns?
> 
> image

Done!

**Pull request merged**
