### PR TITLE
feat: basic theme customization

### LINKED ISSUE #9: Basic theme customization
Todo: explain the basics of theme customization by example and explanation.

### PR DESCRIPTION
**Pull request by iuioiua**
This PR defines `primary` and `secondary` colors within `twind.config.js` for the site-wide theme, providing a foundation for further theme customization. A corresponding section within the README was also added. This can be expanded upon in the future if need be.

Closes #9.

### CODE REVIEW

**Comment by iuioiua** [comment]
@hashrock, do you know how to get these preview deployments to read the environment secrets I've defined on the settings page?

**Comment by kt3k** [comment]
Deno Deploy still can read env variable in preview deployment, but if the env var is set in the project, then preview deployments are only created for `push` event of the origin repository, and it doesn't create previews for PRs from forks (to prevent stealing env vars from fork PRs)

**Comment by iuioiua** [comment]
Hm... I see. Are there any workarounds? I want to be able to preview deployments before merging PRs. One alternative that comes to mind is to change any code requiring environmental variables so that it's no longer required but skipped in some way. Simpler, repo-level options would be preferred.

**Comment by kt3k** [comment]
> Hm... I see. Are there any workarounds?

I think the simple workaround is to move your branch to this repo and directly push to there (that causes `push` event and preview should be available even with env vars).

**Pull request merged**
