### PR TITLE
fix: redirect to home page after project created

### PR DESCRIPTION
**Pull request by harshmangalam**

### CODE REVIEW

**Review by iuioiua — APPROVED** [review]
LGTM. Thank you.

**Review by iuioiua — CHANGES_REQUESTED** [review]
Actually, please fix the test case.

**Comment by harshmangalam** [comment]
@iuioiua  fixed tests cases

**Review by iuioiua — CHANGES_REQUESTED** [review]
Can you please revert the formatting changes. These changes are unrelated to the PR's objective and add noise to the diff.

**Comment by harshmangalam** [comment]
@iuioiua fixed fmt issues

**Comment by iuioiua** [comment]
Closes #584

**Review by iuioiua — APPROVED** [review]
LGMT. Thank you.

**Pull request merged**
