### PR TITLE
chore: upgrade to Fresh v1.4.2

### PR DESCRIPTION
**Pull request by iuioiua**
References:
* https://deno.com/blog/fresh-1.4#faster-page-loads-with-ahead-of-time-compilation
* https://fresh.deno.dev/docs/concepts/ahead-of-time-builds

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]
LGTM, I'm not sure why the CI is failing with a KV migration error.

**Comment by iuioiua** [comment]
@losfair, any idea about the CI failure?

**Comment by losfair** [comment]
The failure is likely caused by https://github.com/denoland/deno/issues/20116, which is fixed in https://github.com/denoland/deno/pull/20189. For now, retrying the CI step should help.

**Comment by iuioiua** [comment]
I'll wait until a new version of the Deno runtime is released before merging this PR.

**Pull request merged**
