### PR TITLE
refactor: use `define*()` helpers

### PR DESCRIPTION
**Pull request by harshmangalam**

### CODE REVIEW

**Comment by iuioiua** [comment]
I'm 50/50 on this change. Either way, can you please resolve the merge conflicts? Would you also be able to implement this exact change across all the routes? It'd be best to keep consistency.

**Comment by harshmangalam** [comment]
Okay  @iuioiua  I will fix conflict and will implement this exact change across all the routes.

**Comment by harshmangalam** [comment]
@iuioiua  fixed conflicts and implemented across all routes here https://github.com/denoland/saaskit/pull/590

**Comment by iuioiua** [comment]
@harshmangalam, why did you close the PR?

**Comment by harshmangalam** [comment]
This PR is not of any use instead i have add  #590

**Comment by iuioiua** [comment]
I don't realise you had 2 PRs open. Next time, please just update the current one instead of opening a new one if it has enough overlap 👍🏾

**Pull request closed without merging**
