### PR TITLE
refactor: rework notifications pages

### PR DESCRIPTION
**Pull request by iuioiua**
This change simplifies the logic around the notifications page and makes it less hacky. A few styling changes have also been made.

### CODE REVIEW

**Comment by iuioiua** [comment]
@marvinhagemeister, type checks aren't liking `/routes/notifications/index.tsx`. Is this a bug or error on my part?

**Comment by kt3k** [comment]
There seems something wrong in `AsyncRoute` typing https://github.com/denoland/fresh/blob/9cae8fdd5cb31f920efc10402d01da31ab9e90ac/src/server/types.ts#L138

Specifying `SignedInState` in `ctx: RouteContext<unknown, SignedInState>` makes `NotificationsPage` incompatible with `AsyncRoute` (I guess this should be fixed in fresh side)

**Comment by iuioiua** [comment]
Nice catch! Fix incoming.

**Comment by iuioiua** [comment]
Hm... I remove the state type and still have the same issue...

**Comment by iuioiua** [comment]
I've reverted to the handler method for now. I can refactor once the fix has been published to Fresh.

**Pull request merged**
