### PR TITLE
feat: improve page selector UI

### PR DESCRIPTION
**Pull request by brunocorrea23**
Changing Page Select (pagination) UI as suggested by @hashrock in #346 

Before:
Screenshot 2023-08-05 at 11 45 12

Now:
Screenshot 2023-08-05 at 11 45 27

### CODE REVIEW

**Review by hashrock — APPROVED** [review]
LGTM!

**Comment by brunocorrea23** [comment]
@iuioiua , what do you think about this proposal here?

**Comment by iuioiua** [comment]
Hi Bruno, sorry for the delay in getting back to you. Check out #414. There I lay out my reason as to why we should go back to `cursor`-based pagination. While I love the look of what you designed, it conflicts with my proposal.

**Comment by brunocorrea23** [comment]
Makes sense! we should use the cursor for pagination. 
But I'd still suggest we use the numbers pagination. We would have to adapt it so that it doesn't load all the info at once, but we can make it work.
Let me take a look at it and I'll send a PR.

**Pull request closed without merging**
